services:
  - type: web
    name: cofo-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    domains:
      - cofo.pl
      - www.cofo.pl
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
